#!/usr/bin/env bash
# Copyright (C) 2025 T-Systems International GmbH.
#
# You can find the compulsory statement on:
# https://www.t-systems.com/de/en/compulsory-statement
#
# All rights, including licensing, inspection, modification and sharing of
# software and source code, reserved.

set -euo pipefail

echo "🚀 Running global pre-commit ..."
pre-commit hook-impl \
  --config ~/.config/git/core/pre-commit-config.yml \
  --hook-type=pre-commit \
  -- "$@"

if [ -f "$(pwd)/.git/hooks/pre-commit" ]; then
  echo "🚀 Running local pre-commit ..."
  exec $(pwd)/.git/hooks/pre-commit "$@"
else
  if [ -f ".pre-commit-config.yaml" ]; then
    echo "Detected local pre-commit config, installing ..."
    pre-commit install
    exec $(pwd)/.git/hooks/pre-commit "$@"
  fi
fi
